# This is a basic workflow to help you get started with Actions

name: tag

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
